version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 3312:3306
    volumes:
      - db:/var/lib/mysql

  achat-backend:
    depends_on:
      - mysqldb
    image: achat:1.0.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 6868-8089
    volumes:
      - .m2/root/.m2
    stdin_open: true
    tty: true


volumes:
  db: